# Generated by Django 4.2.5 on 2023-09-11 18:23

from django.db import migrations, models
import ecomerce_slider.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('link', models.URLField(verbose_name='ادس')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to=ecomerce_slider.models.upload_image_path, verbose_name='عکس')),
            ],
        ),
    ]
