version: '3.7'

services:
  app:
    build: './app'
    container_name: 'app'
    restart: 'always'
    expose:
      - '8000'
    volumes:
      - type: 'bind'
        source: './volumes/app'
        target: '/app'
      
  nginx:
    build: './nginx'
    container_name: 'nginx'
    restart: always
    ports:
      - '80:80'
    volumes:
      - type: 'bind'
        source: './volums/app/static_cdn/media_root'
        target: 'app/static_cdn/media_root'
      - type: 'bind'
        source: './volums/app/static_cdn/static_root'
        target: 'app/static_cdn/static_root'