# Generated by Django 4.2.5 on 2023-09-27 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_order', '0002_alter_order_date_payid_alter_order_is_payid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_payid',
            new_name='date_paid',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_payid',
            new_name='is_paid',
        ),
    ]
