# Generated by Django 4.2.5 on 2023-09-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_catagory', '0002_alter_productcatagory_options'),
        ('ecomerce_products', '0003_alter_product_options_alter_product_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagories',
            field=models.ManyToManyField(blank=True, to='ecomerce_catagory.productcatagory', verbose_name='دسته بندی ها'),
        ),
    ]
