# Generated by Django 4.2.5 on 2023-09-24 05:30

from django.db import migrations, models
import django.db.models.deletion
import ecomerce_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_products', '0005_productgallary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallary',
            name='image',
            field=models.ImageField(upload_to=ecomerce_products.models.upload_gallary_image_path, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='productgallary',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomerce_products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productgallary',
            name='title',
            field=models.CharField(max_length=120, verbose_name='عنوان'),
        ),
    ]
