# Generated by Django 5.0b1 on 2023-11-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_products', '0007_product_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_manufacturer',
            field=models.CharField(default='لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت', max_length=120, verbose_name='درباره سازنده'),
        ),
    ]
