# Generated by Django 4.2.5 on 2023-09-26 06:13

from django.db import migrations, models
import ecomerce_setting.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ecomerce_setting.models.upload_image_path, verbose_name='عکس لوگو'),
        ),
    ]
