# Generated by Django 4.2.5 on 2023-09-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدرها'},
        ),
    ]
