# Generated by Django 4.2.5 on 2023-09-10 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'تگ', 'verbose_name_plural': 'تگ ها'},
        ),
    ]
