# Generated by Django 4.2.5 on 2023-09-10 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_catagory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcatagory',
            options={'verbose_name': 'گروه', 'verbose_name_plural': 'گروه ها'},
        ),
    ]
