# Generated by Django 4.2.5 on 2023-09-07 18:24

from django.db import migrations, models
import ecomerce_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=ecomerce_products.models.upload_image_path),
        ),
    ]
