# Generated by Django 4.2.5 on 2023-09-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_products', '0006_alter_productgallary_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visit_count',
            field=models.IntegerField(default=0, verbose_name='پربازدیدترین محصولات'),
        ),
    ]
