# Generated by Django 4.2.5 on 2023-09-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_payid',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_payid',
            field=models.BooleanField(verbose_name='خریداری شده / نشده'),
        ),
    ]
